services:
  - type: web
    name: Django Project
    runtime: python
    env: python
    envVars:
      - key: POETRY_ENABLED
        value: false
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python -m gunicorn project_organization.wsgi:application
