services:
  - type: web
    name: django-project-organization
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && gunicorn project_organization.wsgi:application"
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: django-project-db
          property: connectionString
    databases:
      - name: django-project-db
        plan: free
